name: my_dev_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - flask=2.1.3
  - scikit-learn
  - numpy
  - pandas
  - matplotlib=3.9.2
  - jupyterlab
  - h5py
  - networkx
  - nltk
  - pytest
  - pyqt
  - lxml
  - pytz
  - pywin32
  - pyzmq
  - seaborn
  - scipy
  - statsmodels
  - sqlalchemy
  - streamlit
  - widgetsnbextension
  - zstandard
  - pip
  - pip:
      - uvicorn[standard]==0.27.0
      - gunicorn==21.2.0
      - Werkzeug==2.1.2
      - matplotlib-inline
      - PyQt5==5.15.10
      - PyQtWebEngine==5.15.6
      - grpcio==1.68.1
      - keras==3.7.0
      - pyarrow
      - orjson==3.10.12
      - plotly
      - pywavelets
      - python-slugify
      - python-dateutil
      - python-dotenv
      - pandas
      - psutil
      - protobuf==4.25.3
      - pillow
      - hvplot
      - fastjsonschema
      - flake8
      - numexpr
      - PyJWT
      - PyDrive2==1.21.3
      - jsonschema
      - jsonpatch
      - joblib
      - pywinpty
      - PyYAML
      - torch==2.5.1
      - torchvision==0.20.1
      - torchaudio==2.5.1
      - tensorflow==2.18.0
      - tensorboard==2.18.0
      - termcolor==2.5.0
      - yapf
      - xarray
      - xlwings
      - zope.interface
# Package                      Version
# ---------------------------- -----------
# absl-py                      2.1.0
# altair                       5.0.1
# anyio                        4.6.2
# argon2-cffi                  21.3.0
# argon2-cffi-bindings         21.2.0
# asttokens                    2.0.5
# astunparse                   1.6.3
# async-lru                    2.0.4
# attrs                        24.3.0
# Babel                        2.11.0
# backcall                     0.2.0
# beautifulsoup4               4.12.3
# bleach                       6.2.0
# blinker                      1.6.2
# bokeh                        3.4.3
# Bottleneck                   1.4.2
# Brotli                       1.0.9
# cachetools                   5.3.3
# certifi                      2024.12.14
# cffi                         1.17.1
# charset-normalizer           3.3.2
# click                        8.1.7
# colorama                     0.4.6
# colorcet                     3.1.0
# comm                         0.2.1
# contourpy                    1.2.0
# cryptography                 43.0.3
# cycler                       0.11.0
# debugpy                      1.6.7
# decorator                    5.1.1
# defusedxml                   0.7.1
# exceptiongroup               1.2.0
# executing                    0.8.3
# fastjsonschema               2.21.1
# filelock                     3.16.1
# flake8                       7.1.1
# Flask                        2.1.3
# flatbuffers                  24.12.23
# fonttools                    4.51.0
# fsspec                       2024.12.0
# gast                         0.6.0
# gitdb                        4.0.7
# GitPython                    3.1.43
# google-api-core              2.24.0
# google-api-python-client     2.156.0
# google-auth                  2.37.0
# google-auth-httplib2         0.2.0
# google-pasta                 0.2.0
# googleapis-common-protos     1.66.0
# graphviz                     0.20.1
# greenlet                     3.1.1
# grpcio                       1.68.1
# gunicorn                     21.2.0
# h11                          0.14.0
# h5py                         3.12.1
# holoviews                    1.20.0
# httpcore                     1.0.2
# httplib2                     0.22.0
# httptools                    0.6.4
# httpx                        0.27.0
# hvplot                       0.11.2
# idna                         3.7
# importlib_metadata           8.5.0
# importlib_resources          6.4.0
# iniconfig                    1.1.1
# ipykernel                    6.29.5
# ipython                      8.15.0
# ipywidgets                   8.1.5
# itsdangerous                 2.2.0
# jedi                         0.19.2
# Jinja2                       3.1.4
# joblib                       1.4.2
# json5                        0.9.25
# jsonpatch                    1.33
# jsonpointer                  3.0.0
# jsonschema                   4.23.0
# jsonschema-specifications    2023.7.1
# jupyter_client               8.6.0
# jupyter_core                 5.7.2
# jupyter-events               0.10.0
# jupyter-lsp                  2.2.0
# jupyter_server               2.14.1
# jupyter_server_terminals     0.4.4
# jupyterlab                   4.2.5
# jupyterlab-pygments          0.1.2
# jupyterlab_server            2.27.3
# jupyterlab_widgets           3.0.13
# keras                        3.7.0
# kiwisolver                   1.4.4
# libclang                     18.1.1
# linkify-it-py                2.0.3
# lxml                         5.3.0
# Markdown                     3.7
# markdown-it-py               2.2.0
# MarkupSafe                   2.1.3
# matplotlib                   3.9.2
# matplotlib-inline            0.1.7
# mccabe                       0.7.0
# mdit-py-plugins              0.4.2
# mdurl                        0.1.0
# mistune                      2.0.4
# mkl_fft                      1.3.11
# mkl_random                   1.2.8
# mkl-service                  2.4.0
# ml-dtypes                    0.4.1
# mpmath                       1.3.0
# namex                        0.0.8
# nbclient                     0.8.0
# nbconvert                    7.16.4
# nbformat                     5.10.4
# nest-asyncio                 1.6.0
# networkx                     3.2.1
# nltk                         3.9.1
# notebook_shim                0.2.3
# numexpr                      2.10.2
# numpy                        1.26.4
# oauth2client                 4.1.3
# opt_einsum                   3.4.0
# optree                       0.13.1
# orjson                       3.10.12
# overrides                    7.4.0
# packaging                    24.2
# pandas                       2.2.3
# pandocfilters                1.5.0
# panel                        1.4.5
# param                        2.2.0
# parso                        0.8.4
# patsy                        0.5.6
# pickleshare                  0.7.5
# pillow                       11.0.0
# pip                          24.3.1
# platformdirs                 3.10.0
# plotly                       5.24.1
# pluggy                       1.5.0
# ply                          3.11
# prometheus_client            0.21.0
# prompt-toolkit               3.0.43
# proto-plus                   1.25.0
# protobuf                     4.25.3
# psutil                       6.1.1
# pure-eval                    0.2.2
# pyarrow                      18.1.0
# pyasn1                       0.6.1
# pyasn1_modules               0.4.1
# pycodestyle                  2.12.1
# pycparser                    2.21
# pydeck                       0.8.0b4
# pydotplus                    2.0.2
# PyDrive2                     1.21.3
# pyflakes                     3.2.0
# Pygments                     2.15.1
# PyJWT                        2.10.1
# pyOpenSSL                    24.2.1
# pyparsing                    3.2.0
# PyQt5                        5.15.10
# PyQt5-sip                    12.13.0
# PyQtWebEngine                5.15.6
# PyQtWebEngine-Qt5            5.15.2
# PySocks                      1.7.1
# pytest                       7.4.4
# python-dateutil              2.9.0.post0
# python-dotenv                1.0.1
# python-json-logger           3.2.1
# python-slugify               8.0.4
# pytz                         2024.1
# pyviz_comms                  3.0.3
# PyWavelets                   1.6.0
# pywin32                      305.1
# pywinpty                     2.0.14
# PyYAML                       6.0.2
# pyzmq                        26.2.0
# referencing                  0.30.2
# regex                        2024.9.11
# requests                     2.32.3
# rfc3339-validator            0.1.4
# rfc3986-validator            0.1.1
# rich                         13.9.4
# rpds-py                      0.10.6
# rsa                          4.9
# scikit-learn                 1.6.0
# scipy                        1.13.1
# seaborn                      0.13.2
# Send2Trash                   1.8.2
# setuptools                   75.6.0
# sip                          6.7.12
# six                          1.16.0
# smmap                        4.0.0
# sniffio                      1.3.0
# soupsieve                    2.5
# SQLAlchemy                   2.0.34
# stack-data                   0.2.0
# statsmodels                  0.14.4
# streamlit                    1.40.1
# sympy                        1.13.1
# tenacity                     9.0.0
# tensorboard                  2.18.0
# tensorboard-data-server      0.7.2
# tensorflow                   2.18.0
# tensorflow_intel             2.18.0
# tensorflow-io-gcs-filesystem 0.31.0
# termcolor                    2.5.0
# terminado                    0.17.1
# text-unidecode               1.3
# threadpoolctl                3.5.0
# tinycss2                     1.2.1
# toml                         0.10.2
# tomli                        2.0.1
# toolz                        0.12.0
# torch                        2.5.1
# torchaudio                   2.5.1
# torchvision                  0.20.1
# tornado                      6.4.2
# tqdm                         4.66.5
# traitlets                    5.14.3
# typing_extensions            4.12.2
# tzdata                       2023.3
# uc-micro-py                  1.0.3
# unicodedata2                 15.1.0
# uritemplate                  4.1.1
# urllib3                      2.2.3
# uvicorn                      0.27.0
# watchdog                     4.0.1
# watchfiles                   1.0.3
# wcwidth                      0.2.5
# webencodings                 0.5.1
# websocket-client             1.8.0
# websockets                   14.1
# Werkzeug                     2.1.2
# wheel                        0.44.0
# widgetsnbextension           4.0.13
# win-inet-pton                1.1.0
# wrapt                        1.17.0
# xarray                       2024.7.0
# xlwings                      0.33.5
# xyzservices                  2024.9.0
# yapf                         0.43.0
# zipp                         3.21.0
# zope.interface               7.2
# zstandard                    0.23.0

# (my_dev_env) C:\Users\dson\dson_llm-dev>pip list
# Package                      Version
# ---------------------------- -----------
# absl-py                      2.1.0
# altair                       5.0.1
# anyio                        4.6.2
# argon2-cffi                  21.3.0
# argon2-cffi-bindings         21.2.0
# asttokens                    2.0.5
# astunparse                   1.6.3
# async-lru                    2.0.4
# attrs                        24.3.0
# Babel                        2.11.0
# backcall                     0.2.0
# beautifulsoup4               4.12.3
# bleach                       6.2.0
# blinker                      1.6.2
# bokeh                        3.4.3
# Bottleneck                   1.4.2
# Brotli                       1.0.9
# cachetools                   5.3.3
# certifi                      2024.12.14
# cffi                         1.17.1
# charset-normalizer           3.3.2
# click                        8.1.7
# colorama                     0.4.6
# colorcet                     3.1.0
# comm                         0.2.1
# contourpy                    1.2.0
# cryptography                 43.0.3
# cycler                       0.11.0
# debugpy                      1.6.7
# decorator                    5.1.1
# defusedxml                   0.7.1
# exceptiongroup               1.2.0
# executing                    0.8.3
# fastjsonschema               2.21.1
# filelock                     3.16.1
# flake8                       7.1.1
# Flask                        2.1.3
# flatbuffers                  24.12.23
# fonttools                    4.51.0
# fsspec                       2024.12.0
# gast                         0.6.0
# gitdb                        4.0.7
# GitPython                    3.1.43
# google-api-core              2.24.0
# google-api-python-client     2.156.0
# google-auth                  2.37.0
# google-auth-httplib2         0.2.0
# google-pasta                 0.2.0
# googleapis-common-protos     1.66.0
# graphviz                     0.20.1
# greenlet                     3.1.1
# grpcio                       1.68.1
# gunicorn                     21.2.0
# h11                          0.14.0
# h5py                         3.12.1
# holoviews                    1.20.0
# httpcore                     1.0.2
# httplib2                     0.22.0
# httptools                    0.6.4
# httpx                        0.27.0
# hvplot                       0.11.2
# idna                         3.7
# importlib_metadata           8.5.0
# importlib_resources          6.4.0
# iniconfig                    1.1.1
# ipykernel                    6.29.5
# ipython                      8.15.0
# ipywidgets                   8.1.5
# itsdangerous                 2.2.0
# jedi                         0.19.2
# Jinja2                       3.1.4
# joblib                       1.4.2
# json5                        0.9.25
# jsonpatch                    1.33
# jsonpointer                  3.0.0
# jsonschema                   4.23.0
# jsonschema-specifications    2023.7.1
# jupyter_client               8.6.0
# jupyter_core                 5.7.2
# jupyter-events               0.10.0
# jupyter-lsp                  2.2.0
# jupyter_server               2.14.1
# jupyter_server_terminals     0.4.4
# jupyterlab                   4.2.5
# jupyterlab-pygments          0.1.2
# jupyterlab_server            2.27.3
# jupyterlab_widgets           3.0.13
# keras                        3.7.0
# kiwisolver                   1.4.4
# libclang                     18.1.1
# linkify-it-py                2.0.3
# lxml                         5.3.0
# Markdown                     3.7
# markdown-it-py               2.2.0
# MarkupSafe                   2.1.3
# matplotlib                   3.9.2
# matplotlib-inline            0.1.7
# mccabe                       0.7.0
# mdit-py-plugins              0.4.2
# mdurl                        0.1.0
# mistune                      2.0.4
# mkl_fft                      1.3.11
# mkl_random                   1.2.8
# mkl-service                  2.4.0
# ml-dtypes                    0.4.1
# mpmath                       1.3.0
# namex                        0.0.8
# nbclient                     0.8.0
# nbconvert                    7.16.4
# nbformat                     5.10.4
# nest-asyncio                 1.6.0
# networkx                     3.2.1
# nltk                         3.9.1
# notebook_shim                0.2.3
# numexpr                      2.10.2
# numpy                        1.26.4
# oauth2client                 4.1.3
# opt_einsum                   3.4.0
# optree                       0.13.1
# orjson                       3.10.12
# overrides                    7.4.0
# packaging                    24.2
# pandas                       2.2.3
# pandocfilters                1.5.0
# panel                        1.4.5
# param                        2.2.0
# parso                        0.8.4
# patsy                        0.5.6
# pickleshare                  0.7.5
# pillow                       11.0.0
# pip                          24.3.1
# platformdirs                 3.10.0
# plotly                       5.24.1
# pluggy                       1.5.0
# ply                          3.11
# prometheus_client            0.21.0
# prompt-toolkit               3.0.43
# proto-plus                   1.25.0
# protobuf                     4.25.3
# psutil                       6.1.1
# pure-eval                    0.2.2
# pyarrow                      18.1.0
# pyasn1                       0.6.1
# pyasn1_modules               0.4.1
# pycodestyle                  2.12.1
# pycparser                    2.21
# pydeck                       0.8.0b4
# pydotplus                    2.0.2
# PyDrive2                     1.21.3
# pyflakes                     3.2.0
# Pygments                     2.15.1
# PyJWT                        2.10.1
# pyOpenSSL                    24.2.1
# pyparsing                    3.2.0
# PyQt5                        5.15.10
# PyQt5-sip                    12.13.0
# PyQtWebEngine                5.15.6
# PyQtWebEngine-Qt5            5.15.2
# PySocks                      1.7.1
# pytest                       7.4.4
# python-dateutil              2.9.0.post0
# python-dotenv                1.0.1
# python-json-logger           3.2.1
# python-slugify               8.0.4
# pytz                         2024.1
# pyviz_comms                  3.0.3
# PyWavelets                   1.6.0
# pywin32                      305.1
# pywinpty                     2.0.14
# PyYAML                       6.0.2
# pyzmq                        26.2.0
# referencing                  0.30.2
# regex                        2024.9.11
# requests                     2.32.3
# rfc3339-validator            0.1.4
# rfc3986-validator            0.1.1
# rich                         13.9.4
# rpds-py                      0.10.6
# rsa                          4.9
# scikit-learn                 1.6.0
# scipy                        1.13.1
# seaborn                      0.13.2
# Send2Trash                   1.8.2
# setuptools                   75.6.0
# sip                          6.7.12
# six                          1.16.0
# smmap                        4.0.0
# sniffio                      1.3.0
# soupsieve                    2.5
# SQLAlchemy                   2.0.34
# stack-data                   0.2.0
# statsmodels                  0.14.4
# streamlit                    1.40.1
# sympy                        1.13.1
# tenacity                     9.0.0
# tensorboard                  2.18.0
# tensorboard-data-server      0.7.2
# tensorflow                   2.18.0
# tensorflow_intel             2.18.0
# tensorflow-io-gcs-filesystem 0.31.0
# termcolor                    2.5.0
# terminado                    0.17.1
# text-unidecode               1.3
# threadpoolctl                3.5.0
# tinycss2                     1.2.1
# toml                         0.10.2
# tomli                        2.0.1
# toolz                        0.12.0
# torch                        2.5.1
# torchaudio                   2.5.1
# torchvision                  0.20.1
# tornado                      6.4.2
# tqdm                         4.66.5
# traitlets                    5.14.3
# typing_extensions            4.12.2
# tzdata                       2023.3
# uc-micro-py                  1.0.3
# unicodedata2                 15.1.0
# uritemplate                  4.1.1
# urllib3                      2.2.3
# uvicorn                      0.27.0
# watchdog                     4.0.1
# watchfiles                   1.0.3
# wcwidth                      0.2.5
# webencodings                 0.5.1
# websocket-client             1.8.0
# websockets                   14.1
# Werkzeug                     2.1.2
# wheel                        0.44.0
# widgetsnbextension           4.0.13
# win-inet-pton                1.1.0
# wrapt                        1.17.0
# xarray                       2024.7.0
# xlwings                      0.33.5
# xyzservices                  2024.9.0
# yapf                         0.43.0
# zipp                         3.21.0
# zope.interface               7.2
# zstandard                    0.23.0